### ISSUE TITLE
Create compatibility with BO4E > v202401.0.0

### ISSUE THREAD

**Issue by lord-haffi** [Hochfrequenz/intermediate-bo4e-migration-models#135]
The current implemented BO4E version is legacy. The newest version has implemented e.g. reworked BO objects and changed some technical fields as `_typ`. It will be a big load of work to adapt ibims to these changes. It may also be necessary to adapt code in powercloud2lynqtech in a next step if fields or models got renamed or if the modelling changed.

Related PR: https://github.com/Hochfrequenz/intermediate-bo4e-migration-models/pull/134

Necessary steps (and knowledge) are:

- [x] Understand how the BO4E-config files work
- [ ] Compare configuration with actual (new) implementation of BO4E
- [ ] Maybe rename fields
- [ ] Maybe remove additional models if they are now implemented in BO4E standard
- [ ] Maybe remove additional fields if they are now implemented in BO4E standard
- [ ] E.g. Move from `BoTyp` to `Typ`
- [ ] Maybe more complicated stuff if the modelling changed
- [ ] Eventually, adapt code in powercloud2lynqtech (out of scope for this issue)

**Comment by hf-kklein** [comment]
I See ;)
